pool:
  vmImage: 'ubuntu-24.04'

trigger:
  branches:
    exclude:
    - master
    # - ci/*
    # include:
    # - ci/azure*

variables:
  CCACHE_DIR: $(Pipeline.Workspace)/ccache

jobs:
- job: clang_analysis
  timeoutInMinutes: 120
  variables:
    CC: ccache clang-18
    CXX: ccache clang++-18
    CFLAGS: -Wextra -Werror
    CXXFLAGS: -Wextra -Werror
  steps:
  - script: uname -a && cat /proc/cpuinfo /proc/meminfo
    displayName: System Information
  - script: sudo add-apt-repository 'ppa:ubuntu-toolchain-r/test' && sudo apt-get update && sudo apt-get install -y ninja-build ninja-build python3-pip python3-setuptools python3-wheel clang-18 clang-tools-18 ccache
    displayName: Install APT Dependencies
  - task: Cache@2
    displayName: Ccache caching
    inputs:
      key: 'ccache | clang | "$(Agent.OS)" | $(Build.SourceVersion)'
      path: $(CCACHE_DIR)
      restoreKeys: |
        ccache | "$(Agent.OS)"
  - script: pip3 install -v meson==0.55.1
    displayName: Install pip Dependencies
  - script: scan-build-18 /home/vsts/.local/bin/meson setup build -Db_sanitize=address,undefined
    displayName: Configure
  - script: scan-build-18 ninja -C build -v
    displayName: Build
  - script: ninja -C build -v test
    displayName: Test
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'build/meson-logs/testlog.junit.xml'

- job: gcc_analysis
  timeoutInMinutes: 240
  variables:
    CC: ccache gcc-13  # as of 2025-02-02, gcc 14.2.0 runs out of memory on Azure and is killed.
    CXX: ccache g++-13
    CFLAGS: -fanalyzer -Wextra -Werror -Wno-analyzer-use-of-uninitialized-value -Wno-analyzer-allocation-size -Wno-analyzer-shift-count-overflow
    CXXFLAGS: -Wextra -Werror
  steps:
  - script: uname -a && cat /proc/cpuinfo /proc/meminfo
    displayName: System Information
  - script: sudo add-apt-repository 'ppa:ubuntu-toolchain-r/ppa' && sudo apt-get update && sudo apt-get install -y ninja-build ninja-build python3-pip python3-setuptools python3-wheel gcc-13 g++-13 ccache
    displayName: Install APT Dependencies
  - task: Cache@2
    displayName: Ccache caching
    inputs:
      key: 'ccache | gcc | "$(Agent.OS)" | $(Build.SourceVersion)'
      path: $(CCACHE_DIR)
      restoreKeys: |
        ccache | "$(Agent.OS)"
  - script: pip3 install meson==0.55.1
    displayName: Install pip Dependencies
  - script: /home/vsts/.local/bin/meson setup build -Db_sanitize=address,undefined
    displayName: Configure
  - script: ninja -C build -v -j1
    # -j1 to conserve memory
    displayName: Build
  - script: ninja -C build -v test
    displayName: Test
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'build/meson-logs/testlog.junit.xml'

# - job: loongson3a
#   container:
#     image: debian:unstable
#     options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
#   steps:
#   # https://github.com/Microsoft/azure-pipelines-agent/issues/2043
#   - script: /tmp/docker exec -t -u 0 ci-container sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
#     displayName: 'Install Sudo in container'
#   - script: uname -a && cat /proc/cpuinfo /proc/meminfo
#     displayName: System Information
#   - script: sudo dpkg --add-architecture mips64el && sudo apt-get update && sudo apt-get install -y ninja-build ninja-build python3-pip python3-setuptools python3-wheel libc6:mips64el gcc-10-mips64el-linux-gnuabi64 g++-10-mips64el-linux-gnuabi64 qemu-user-static
#     displayName: Install APT Dependencies
#   - script: pip3 install meson==0.55.1
#     displayName: Install pip Dependencies
#   - script: /home/vsts/.local/bin/meson setup build --cross-file=docker/cross-files/loongson-gcc-10.cross
#     displayName: Configure
#   - script: ninja -C build -v
#     displayName: Build
#   - script: ninja -C build -v test
#     displayName: Test
