language: c
sudo: false
dist: trusty
branches:
  except:
    - /^(wip\/)?(appveyor|msvc|mingw|windows)(\-.+)?$/
matrix:
  include:
    ###
    ## Linux builds using various versions of GCC.
    ###
    - env: C_COMPILER=gcc-6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-6
          - g++-6
          - cmake
          - cmake-data
    - env: C_COMPILER=gcc-5 BUILD_TYPE=Release
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-5
          - g++-5
          - cmake
          - cmake-data
    # - env: C_COMPILER=gcc-4.9
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - gcc-4.9
    #       - g++-4.9
    #       - cmake
    #       - cmake-data
    - addons:
        apt:
          sources:
          - george-edison55-precise-backports
          packages:
          - cmake
          - cmake-data
    # - env: C_COMPILER=gcc-4.7
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - gcc-4.7
    #       - g++-4.7
    #       - cmake
    #       - cmake-data
    - env: C_COMPILER=gcc-4.6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-4.6
          - g++-4.6
          - cmake
          - cmake-data
    # - os: linux
    #   env: C_COMPILER=gcc-4.5
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - gcc-4.5
    #       - g++-4.5
    #       - cmake
    #       - cmake-data
    - env: C_COMPILER=gcc-4.4
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-4.4
          - g++-4.4
          - cmake
          - cmake-data

    ###
    ## clang on Linux
    ###
    - env: C_COMPILER=clang-3.9
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.9
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - clang-3.9
          - cmake
          - cmake-data
    - env: C_COMPILER=clang-3.8
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.8
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - clang-3.8
          - cmake
          - cmake-data
    # - env: C_COMPILER=clang-3.7
    #   addons:
    #     apt:
    #       sources:
    #       - llvm-toolchain-precise-3.7
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - clang-3.7
    #       - cmake
    #       - cmake-data
    # - env: C_COMPILER=clang-3.6
    #   addons:
    #     apt:
    #       sources:
    #       - llvm-toolchain-precise-3.6
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - clang-3.6
    #       - cmake
    #       - cmake-data
    # - env: C_COMPILER=clang-3.5
    #   addons:
    #     apt:
    #       sources:
    #       - llvm-toolchain-precise-3.5
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - clang-3.5
    #       - cmake
    #       - cmake-data

    ###
    ## PGI
    ###
    - env: C_COMPILER=pgcc
      addons:
        apt:
          sources:
          - george-edison55-precise-backports
          packages:
          - cmake
          - cmake-data

    ###
    ## OS X
    ###
    # - os: osx

before_install:
###
## If we use the matrix to set CC/CXX Travis overwrites the values,
## so instead we use C/CXX_COMPILER, then copy the values to CC/CXX
## here (after Travis has set CC/CXX).
###
- if [ "${C_COMPILER}" = "pgcc" ]; then curl 'https://raw.githubusercontent.com/nemequ/pgi-travis/master/install-pgi.sh' | /bin/sh; fi
- if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
- if [ -n "${BUILD_TYPE}" ]; then export BUILD_TYPE="Coverage"; fi
- mkdir test/build
- cd test/build

script:
- if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
- cmake .. -DCMAKE_BUILD_TYPE="${BUILD_TYPE}"
- make VERBOSE=1
- ./test-native && ./test-emul && ./test-cmp

after_success:
- if [ "${BUILD_TYPE}" = "Coverage" ]; then bash <(curl -s https://codecov.io/bash) -f '!*test-common.c'; fi
