language: c
sudo: false
branches:
  except:
    - /^(wip\/)?(appveyor|msvc|mingw|windows)(\-.+)?$/
    - /^master$/
matrix:
  include:
    ###
    ## Linux builds using various versions of GCC.
    ###
    - env: C_COMPILER=gcc-6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-6
          - g++-6
          - cmake
          - cmake-data
    - env: C_COMPILER=gcc-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-5
          - g++-5
          - cmake
          - cmake-data
    # - env: C_COMPILER=gcc-4.9
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - gcc-4.9
    #       - g++-4.9
    #       - cmake
    #       - cmake-data
    - env: C_COMPILER=gcc-4.8
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-4.8
          - g++-4.8
          - cmake
          - cmake-data
    # - env: C_COMPILER=gcc-4.7
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - gcc-4.7
    #       - g++-4.7
    #       - cmake
    #       - cmake-data
    - env: C_COMPILER=gcc-4.6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-4.6
          - g++-4.6
          - cmake
          - cmake-data
    # - os: linux
    #   env: C_COMPILER=gcc-4.5
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - gcc-4.5
    #       - g++-4.5
    #       - cmake
    #       - cmake-data
    - env: C_COMPILER=gcc-4.4
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-4.4
          - g++-4.4
          - cmake
          - cmake-data

    ###
    ## clang on Linux
    ###
    - env: C_COMPILER=clang-3.9
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.9
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - clang-3.9
          - cmake
          - cmake-data
    - env: C_COMPILER=clang-3.8
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.8
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - clang-3.8
          - cmake
          - cmake-data
    # - env: C_COMPILER=clang-3.7
    #   addons:
    #     apt:
    #       sources:
    #       - llvm-toolchain-precise-3.7
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - clang-3.7
    #       - cmake
    #       - cmake-data
    # - env: C_COMPILER=clang-3.6
    #   addons:
    #     apt:
    #       sources:
    #       - llvm-toolchain-precise-3.6
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - clang-3.6
    #       - cmake
    #       - cmake-data
    # - env: C_COMPILER=clang-3.5
    #   addons:
    #     apt:
    #       sources:
    #       - llvm-toolchain-precise-3.5
    #       - ubuntu-toolchain-r-test
    #       - george-edison55-precise-backports
    #       packages:
    #       - clang-3.5
    #       - cmake
    #       - cmake-data

    ###
    ## PGI
    ###
    # - env: C_COMPILER=pgcc
    #   addons:
    #     apt:
    #       sources:
    #       - george-edison55-precise-backports
    #       packages:
    #       - cmake
    #       - cmake-data

    ###
    ## OS X
    ###
    # - os: osx

before_install:
###
## If we use the matrix to set CC/CXX Travis overwrites the values,
## so instead we use C/CXX_COMPILER, then copy the values to CC/CXX
## here (after Travis has set CC/CXX).
###
- if [ "${C_COMPILER}" = "pgcc" ]; then wget -q -O /dev/stdout 'https://raw.githubusercontent.com/nemequ/pgi-travis/master/install-pgi.sh' | /bin/sh; fi
- if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
- mkdir test/build
- cd test/build

script:
- cmake --version
- cmake .. -DCMAKE_C_COMPILER="${C_COMPILER}" -DCMAKE_C_FLAGS="${CFLAGS}"
- make VERBOSE=1
- ./test-native && ./test-emul
