language: c
cache: ccache
branches:
  except:
    - /^(wip\/)?(appveyor|msvc|mingw|windows)(\-.+)?$/
matrix:
  include:
    - env: C_COMPILER=gcc CFLAGS=-march=native
      addons:
        apt:
          packages:
          - cmake
          - cmake-data
    - env: C_COMPILER=i686-linux-gnu-gcc-8 CFLAGS=-march=i686
      dist: bionic
      addons:
        apt:
          packages:
          - gcc-8-i686-linux-gnu
          - libc6-dev-i386-cross
          - cmake
          - cmake-data
    - env:
        - C_COMPILER=i686-linux-gnu-gcc-8
        - CFLAGS='-march=i686 -DSIMDE_NO_SHUFFLE_VECTOR -mno-avx2 -mno-avx -mno-sse4.2 -mno-sse4.1 -mno-ssse3 -mno-sse3'
      dist: bionic
      addons:
        apt:
          packages:
          - gcc-8-i686-linux-gnu
          - libc6-dev-i386-cross
          - cmake
          - cmake-data
    - env: C_COMPILER=clang CFLAGS=-march=native
      addons:
        apt:
          packages:
          - clang
          - cmake
          - cmake-data
    - env: C_COMPILER=gcc-4.4 CFLAGS=-march=native
      dist: trusty
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-4.4
          - g++-4.4
          - cmake
          - cmake-data
    - env: C_COMPILER=aarch64-linux-gnu-gcc
      addons:
        apt:
          packages:
          - gcc-aarch64-linux-gnu
          - g++-aarch64-linux-gnu
          - qemu
          - cmake
          - cmake-data
    - env: C_COMPILER=clang-3.5 CFLAGS=-march=native
      dist: trusty
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.5
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - clang-3.5
          - cmake
          - cmake-data
    - env: C_COMPILER=pgcc BUILD_TYPE=Debug
      addons:
        apt:
          packages:
          - cmake
          - cmake-data
    - os: osx
    # - env: C_COMPILER=emcc BUILD_TYPE=Debug
    #   addons:
    #     apt:
    #       packages:
    #       - cmake
    #       - cmake-data

before_install:
###
## If we use the matrix to set CC/CXX Travis overwrites the values,
## so instead we use C/CXX_COMPILER, then copy the values to CC/CXX
## here (after Travis has set CC/CXX).
###
- if [ "${C_COMPILER}" = "pgcc" ]; then
    curl 'https://raw.githubusercontent.com/nemequ/pgi-travis/master/install-pgi.sh' | /bin/sh;
  elif [ "${C_COMPILER}" = "emcc" ]; then
    cd "${HOME}";
    curl -L https://github.com/urho3d/emscripten-sdk/archive/master.tar.gz | tar zx;
    . emscripten-sdk-master/emsdk_env.sh;
    SIMDE_CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=${EMSDK}/emscripten/master/cmake/Modules/Platform/Emscripten.cmake -DDISABLE_X86=yes";
  elif [ "${C_COMPILER}" = "arm-linux-gnueabihf-gcc" ]; then
    SIMDE_CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/test/cmake/toolchain-arm-linux-gnueabihf.cmake";
  elif [ "${C_COMPILER}" = "aarch64-linux-gnu-gcc" ]; then
    SIMDE_CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/test/cmake/toolchain-aarch64-linux-gnu.cmake";
  elif [ "${C_COMPILER}" = "i686-linux-gnu-gcc-8" ]; then
    sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt install libc6:i386 ;
  fi
- if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
- if [ -z "${BUILD_TYPE}" ]; then export BUILD_TYPE="Coverage"; fi
- mkdir "${TRAVIS_BUILD_DIR}/test/build"
- cd "${TRAVIS_BUILD_DIR}/test/build"

script:
- if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
- cat /proc/cpuinfo || true
- cmake .. -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_C_FLAGS="-DTRAVIS_CI ${CFLAGS}" ${SIMDE_CMAKE_ARGS}
- make VERBOSE=1
- if [ "${C_COMPILER}" = "arm-linux-gnueabihf-gcc" ]; then
    qemu-arm ./run-tests;
  elif [ "${C_COMPILER}" = "aarch64-linux-gnu-gcc" ]; then
    qemu-aarch64 ./run-tests;
  else
    ./run-tests ;
  fi

after_success:
- if [ "${BUILD_TYPE}" = "Coverage" ]; then bash <(curl -s https://codecov.io/bash) -f '!*test-common.c'; fi
